#!/bin/bash

SLEEP=$1
DIR=$2

function fatal
{
    echo -e "$1\n" >&2
    exit 1
}

function usage
{
    fatal "Usage:

second-cron <sleep in seconds> <path to directory with scripts>"
}

if [ -z "$SLEEP" ] || [ -z "$DIR" ]; then
    usage
fi

if [ ! -d "$DIR" ]; then
    fatal "ERROR: '$DIR' doesn't exist or not a directory"
fi

while :; do
    for file in "$DIR"/*; do
        if [ -x "$file" ]; then
            run-one "$file" &
        fi
    done
    sleep $SLEEP
done
