#!/bin/bash

SLEEP=$1
DIR=$2
RUNONE=$3

function fatal
{
    echo -e "$1\n" >&2
    exit 1
}

function usage
{
    fatal "Usage:

second-cron <sleep in seconds> <path to directory with scripts> <path to run-one script>"
}

if [ -z "$SLEEP" ] || [ -z "$DIR" ] || [ -z "$RUNONE" ]; then
    usage
fi

if [ ! -d "$DIR" ]; then
    fatal "ERROR: '$DIR' doesn't exist or not a directory"
fi

if [ ! -x "$RUNONE" ]; then
    fatal "ERROR: '$RUNONE' is not executable"
fi

while :; do
    for file in "$DIR"/*; do
        if [ -x "$file" ]; then
            $RUNONE "$file" &
        fi
    done
    sleep $SLEEP
done
